
- name: Install WireGuard and related packages
  apt:
    name:
      - wireguard
      - resolvconf
      - vim
    state: present

- name: Generate WireGuard private key
  command: wg genkey
  register: wg_private_key

- name: Save private key to file
  copy:
    content: "{{ wg_private_key.stdout }}"
    dest: /etc/wireguard/private.key
    mode: '0600'

- name: Generate WireGuard public key from private key
  shell: echo "{{ wg_private_key.stdout }}" | wg pubkey
  register: wg_public_key

- name: Save public key to file
  copy:
    content: "{{ wg_public_key.stdout }}"
    dest: /etc/wireguard/public.key
    mode: '0644'

- name: Create client directory for WireGuard keys
  file:
    path: /etc/wireguard/client
    state: directory
    mode: '0755'
  become: yes


# client key creation
# gias key
- name: Generate private key for gias client
  shell: wg genkey | tee /etc/wireguard/client/gias_private_key
  register: gias_private_key
  become: yes

- name: Generate public key for gias client
  shell: cat /etc/wireguard/client/gias_private_key | wg pubkey
  register: gias_public_key
  become: yes

- name: Save gias public key to file
  copy:
    content: "{{ gias_public_key.stdout }}"
    dest: /etc/wireguard/client/gias_public_key
    mode: '0644'

# sudarsan key
- name: Generate private key for sudarsan client
  shell: wg genkey | tee /etc/wireguard/client/sudarsan_private_key
  register: sudarsan_private_key
  become: yes

- name: Generate public key for sudarsan client
  shell: cat /etc/wireguard/client/sudarsan_private_key | wg pubkey
  register: sudarsan_public_key
  become: yes

- name: Save sudarsan public key to file
  copy:
    content: "{{ sudarsan_public_key.stdout }}"
    dest: /etc/wireguard/client/sudarsan_public_key
    mode: '0644'

# foysal key
- name: Generate private key for foysal client
  shell: wg genkey | tee /etc/wireguard/client/foysal_private_key
  register: foysal_private_key
  become: yes

- name: Generate public key for foysal client
  shell: cat /etc/wireguard/client/foysal_private_key | wg pubkey
  register: foysal_public_key
  become: yes

- name: Save foysal public key to file
  copy:
    content: "{{ foysal_public_key.stdout }}"
    dest: /etc/wireguard/client/foysal_public_key
    mode: '0644'


# masnun key
- name: Generate private key for masnun client
  shell: wg genkey | tee /etc/wireguard/client/masnun_private_key
  register: masnun_private_key
  become: yes

- name: Generate public key for masnun client
  shell: cat /etc/wireguard/client/masnun_private_key | wg pubkey
  register: masnun_public_key
  become: yes

- name: Save masnun public key to file
  copy:
    content: "{{ masnun_public_key.stdout }}"
    dest: /etc/wireguard/client/masnun_public_key
    mode: '0644'


# key file close
- name: Create WireGuard configuration file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0644'

# client conf file
- name: Create WireGuard gias file
  template:
    src: giasuddin.conf.j2
    dest: /etc/wireguard/client/giasuddin.conf
    mode: '0644'

- name: Create WireGuard sudarsan file
  template:
    src: sudarsan.conf.j2
    dest: /etc/wireguard/client/sudarsan.conf
    mode: '0644'

- name: Create WireGuard masnun file
  template:
    src: masnun.conf.j2
    dest: /etc/wireguard/client/masnun.conf
    mode: '0644'

- name: Create WireGuard foysal file
  template:
    src: foysal.conf.j2
    dest: /etc/wireguard/client/foysal.conf
    mode: '0644'

# end client conf file

- name: Enable WireGuard on boot
  systemd:
    name: wg-quick@wg0
    enabled: yes

- name: Start WireGuard service
  systemd:
    name: wg-quick@wg0
    state: started

# Enable IP forwarding by adding to /etc/sysctl.conf
- name: Enable IP forwarding by adding to /etc/sysctl.conf
  shell: echo "net.ipv4.ip_forward = 1" | sudo tee -a /etc/sysctl.conf
  become: yes

# Reload sysctl to apply the changes
- name: Reload sysctl to apply the changes
  command: sysctl -p
  become: yes

- name: Check if WireGuard interface is already up
  shell: ip link show wg0
  register: wg0_interface_check
  ignore_errors: yes
  become: yes

- name: Bring up WireGuard interface if it's not already up
  command: wg-quick up wg0
  when: wg0_interface_check.rc != 0
  become: yes

- name: Restart WireGuard service
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: restarted

# Fetch the WireGuard configuration file to your local machine
- name: Download WireGuard giasuddin file
  fetch:
    src: /etc/wireguard/client/giasuddin.conf
    dest: ./giasuddin.conf
    flat: yes

- name: Download WireGuard sudarsan file
  fetch:
    src: /etc/wireguard/client/sudarsan.conf
    dest: ./sudarsan.conf
    flat: yes

- name: Download WireGuard masnun file
  fetch:
    src: /etc/wireguard/client/masnun.conf
    dest: ./masnun.conf
    flat: yes

- name: Download WireGuard foysal file
  fetch:
    src: /etc/wireguard/client/foysal.conf
    dest: ./foysal.conf
    flat: yes

